version: '3.6'

services:
  verdaccio:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: verdaccio/verdaccio:latest
    container_name: 'verdaccio'
    user: "10001:10001" # Run as Verdaccio's default UID/GID
    networks:
      - node-network
    environment:
        - .env
    ports:
      - '${HOST_PORT}:4873'
    volumes:
      - './verdaccio/storage:/verdaccio/storage'
      - './verdaccio/config:/verdaccio/conf'
      - './verdaccio/plugins:/verdaccio/plugins'
      - ./scripts:/scripts
    restart: unless-stopped

networks:
  node-network:
    driver: bridge